package com.example.ui.text

import androidx.annotation.StyleRes
import com.nutapos.nutatest.core.ui.R

enum class TypographyStyle(@StyleRes val style: Int) {
    BODY_SMALL_REGULAR_DEFAULT(R.style.BodySmallRegularDefault),
    BODY_SMALL_REGULAR_SUCCESS(R.style.BodySmallRegularSuccess),
    BODY_MODERATE_REGULAR_DEFAULT(R.style.BodyModerateRegularDefault),
    CAPTION_MODERATE_REGULAR_DEFAULT(R.style.CaptionModerateRegularDefault),
    CAPTION_MODERATE_MEDIUM_DEFAULT(R.style.CaptionModerateMediumDefault),
    CAPTION_MODERATE_MEDIUM_WARNING(R.style.CaptionModerateMediumWarning),
    CAPTION_SMALL_REGULAR_DEFAULT(R.style.CaptionSmallRegularDefault),
    CAPTION_SMALL_REGULAR_WHITE(R.style.CaptionSmallRegularWhite),
    CAPTION_SMALL_MEDIUM_SUCCESS(R.style.CaptionSmallMediumSuccess),
    CAPTION_SMALL_MEDIUM_DEFAULT(R.style.CaptionSmallMediumDefault),
    TITLE_LARGE_BOLD_DEFAULT(R.style.TitleLargeBoldDefault),
    TITLE_MODERATE_BOLD_DEFAULT(R.style.TitleModerateBoldDefault),
    TITLE_MODERATE_BOLD_WHITE(R.style.TitleModerateBoldWhite),
    TITLE_MODERATE_MEDIUM_WHITE(R.style.TitleModerateMediumDefault),
    TITLE_SMALL_BOLD_SUCCESS(R.style.TitleSmallBoldSuccess),
    TITLE_SMALL_BOLD_DEFAULT(R.style.TitleSmallBoldDefault),
    TITLE_SMALL_BOLD_WHITE(R.style.TitleSmallBoldWhite),
    TITLE_SMALL_MEDIUM_SUCCESS(R.style.TitleSmallMediumSuccess),
    TITLE_SMALL_MEDIUM_DANGER(R.style.TitleSmallMediumError),
    TITLE_SMALL_MEDIUM_DEFAULT(R.style.TitleSmallMediumDefault),
    TITLE_TINY_BOLD_SUCCESS(R.style.TitleTinyBoldSuccess),
    TITLE_TINY_BOLD_WHITE(R.style.TitleTinyBoldWhite),
    TITLE_TINY_BOLD_DEFAULT(R.style.TitleTinyBoldDefault),
    TITLE_TINY_BOLD_INACTIVE(R.style.TitleTinyBoldInactive),
    TITLE_TINY_BOLD_WARNING(R.style.TitleTinyBoldWarning),
    TITLE_SMALL_MEDIUM_WHITE(R.style.TitleSmallMediumWhite),
    TITLE_HERO_BOLD_DEFAULT(R.style.TitleHeroBoldDefault),
    TITLE_TINY_MEDIUM_DEFAULT(R.style.TitleTinyMediumDefault),
    CAPTION_MODERATE_REGULAR_SUCCESS(R.style.CaptionModerateRegularSuccess),
    CAPTION_SMALL_MEDIUM_DANGER(R.style.CaptionSmallMediumDanger),
    TITLE_TINY_BOLD_DANGER(R.style.TitleTinyBoldDanger),
    BODY_SMALL_REGULAR_DANGER(R.style.BodyModerateRegularDanger),
    TITLE_LARGE_MEDIUM_DEFAULT(R.style.TitleLargeMediumDefault),
    TITLE_MODERATE_REGULAR_DEFAULT(R.style.TitleModerateRegularDefault),
    CAPTION_MODERATE_REGULAR_DANGER(R.style.CaptionModerateRegularDanger),
    TITLE_SMALL_MEDIUM_INACTIVE(R.style.TitleSmallMediumInactive),
    CAPTION_SMALL_REGULAR_INACTIVE(R.style.CaptionSmallRegularInactive),
    TITLE_EXTRALARGE_BOLD_DEFAULT(R.style.TitleExtraLargeBoldDefault),
    TITLE_TINY_MEDIUM_WHITE(R.style.TitleTinyMediumWhite),
    CAPTION_SMALL_MEDIUM_WHITE(R.style.CaptionSmallMediumWhite),
    CAPTION_SMALL_MEDIUM_WARNING(R.style.CaptionSmallMediumWarning),
    TITLE_TINY_MEDIUM_SUCCESS(R.style.TitleTinyMediumSuccess),
}
